# -*- coding: utf-8 -*-
"""Exercício _logica_de_prog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZqWpHw4da83X661fBh7es_zGMpki6gP4

Lógica de Programação 1 - Exercicios

*   Aula 00 - Introdução, Jupyter e variáveis
*   Aula 01 - Tipo de dados, input/outpurt e operadores matemáticos
"""

#exercício 01

nome = input('Qual o seu nome?')
print(f"Olá, muito bom te ter por aqui {nome}")

#exercício 02

temp_farenheit = float(input("Digite a temperatura em farenheit:"))
temp_celcius = (temp_farenheit - 32)*5/9

print(f"A conversão de {temp_farenheit} F equivale a {temp_celcius} C")

#exercício 03

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} * {num2} = {num1 * num2}")
print(f"{num1} / {num2} = {num1 / num2}")

#exercício 04

comp = float(input("Digite o comprimento do retangulo (em cm): "))
larg = float(input("Digite o largura do retangulo (em cm): "))
area = comp*larg
print(f"A area do retangulo é de {area} cm ")

#exercício 05

conta = float(input("Digite o valor total da conta: "))
gorjeta = float(input("Qual o percentual que deseja dar de gojeta: "))
conta_com_gorjeta = conta + (conta*(gorjeta/100))

print(f"Dado os {gorjeta}% de gorjeta o novo valor a ser pago é de {conta_com_gorjeta} reais")

#exercício 06

reais = float(input("Digite a quantia que deseja converter (em reais): "))
bitcoin = reais/144724.77
print(f" {reais}R$ equivalem a {bitcoin} bitcoin ")

#exercício 07

ano_atual = int(input("Digite em que ano estamos: "))
ano_nascimento = int(input("Digite o ano em que nasceu: "))
print(f"Você tem {ano_atual-ano_nascimento} anos")

#exercício 08

principal = float(input("Digite, em reais, o valor que será aplicado juros: "))
taxa = float(input("Digite o valor da taxa de juros: "))
tempo = float(input("Digite em quanto tempo no qual a tx será aplicada (meses): "))

print(f" A uma tx de {taxa}% e em {tempo} meses o valor do juros é de {principal*(taxa/100)*tempo} reais")

#exercício 09

preco = float(input("Digite o preço sem desconto: "))
desconto = float(input("Digite de quantos porcento é o desconto: "))
preco_final = preco - (preco*(desconto/100))
print(f"O preço final é de {preco_final} reais.")

#exercício 10

x1 = float(input("Digite a coordenada x do primeiro ponto: "))
y1 = float(input("Digite a coordenada y do primeiro ponto: "))
x2 = float(input("Digite a coordenada x do segundo ponto: "))
y2 = float(input("Digite a coordenada y do segundo ponto: "))

dintancia = (((x2-x1)**2) +((y2-y1)**2))**0.5

print(f"A dintância entre os dois pontos é de {dintancia}")

#exercício 11


nota1 = float(input("Digite nota da primeira prova: "))
peso1 = float(input("Digite o peso da primeira prova: "))
nota2 = float(input("Digite nota da primeira prova: "))
peso2 = float(input("Digite o peso da primeira prova: "))

media_ponderada = ((nota1*peso1)+(nota2*peso2))/(peso1+peso2)

print(f"Sua média é de {media_ponderada}")

#exercício 12

valor_em_s = float(input("Digite um valor em segundos"))
uma_hora = 3600
um_min = 60

em_hora = valor_em_s//uma_hora

resto_hora = valor_em_s%uma_hora

em_min = resto_hora//um_min

resto_min = resto_hora%um_min

em_seg = resto_min

print(f"O valor digitado corresponde a {em_hora}h {em_min}min {em_seg}s. ")

#exercício 13

qntd_combustivel = float(input('Qual a quantidade de combustivel no veículo: '))
consumo_medio = int(input("Qual o consumo médio do veículo? (em km/l)"))

autonomia = qntd_combustivel*consumo_medio

print(f"A autonomia do veículo é de {autonomia}km")

#exercício 14
altura = float(input("Digite sua altura:"))
peso = float(input("Digite seu peso:"))

imc = peso/(altura**2)

print(f"Seu IMC é de {imc}")

"""

*   Aula 02 - Operadores lógicos e estruturas de decisão


"""

#exercício 01
num1 = float(input("Digite um número qualquer: "))
num2 = float(input("Digite um número qualquer: "))
num1_maior = num1 > num2
num2_maior = num2 > num1
iguis = num1 == num2

if num1_maior:
  print(f"O maior deles é {num1}")
elif num2_maior:
  print(f"O maior deles é {num2}")
else:
  print("Os numeros são iguais")

#exercício 02

num = float(input("Digite um número qualquer:"))
positivo = num >= 0
negativo = num < 0

if positivo:
  print(f"O valor {num} é positivo")
else:
  print(f"O valor {num} é negativo")

#exercício 03

sexo = input("Digite a letra inicial do seu sexo biológico:").upper()
feminino = sexo == "F"
masculino = sexo == "M"

if feminino:
  print("Pessoa do sexo feminino")
elif masculino:
  print("Pessoa do sexo masculino")
else:
  print("Sexo inválido")

#exercício 04

letra_digitada = input("Digite uma letra qualquer:").lower()
vogal = letra_digitada == "a" or letra_digitada == "e" or letra_digitada == "i" or letra_digitada == "o" or letra_digitada == "u"

if vogal:
  print(f"A letra digitada {letra_digitada} é uma vogal")
else:
  print(f"A letra digitada {letra_digitada} é uma consoante")

#exercicio 05

nota1 = float(input("DIgite a nota da primeira prova:"))
nota2 = float(input("DIgite a nota da segunda prova:"))
media = (nota1+nota2)/2
aprovado = media >= 7
reprovado = media < 7
aprovado_distincao = media == 10

if aprovado_distincao:
  print(f"O aluno foi aprovado com distinção sua média foi de {media}.")
elif aprovado:
  print(f"O aluno foi aprovado, sua média foi de {media}.")
else:
  print(f"O aluno foi reprovado, sua média foi de {media}.")

#exercício 06

preco1 = float(input("Digite o preço do primeiro produto que deseja comprar: "))
preco2 = float(input("Digite o preço do segundo produto que deseja comprar: "))
preco3 = float(input("Digite o preço do terceiro produto que deseja comprar: "))

preco1_menor = preco1 < preco2 and preco1 < preco3
preco2_menor = preco2 < preco1 and preco2 < preco3
preco3_menor = preco3 < preco1 and preco3 < preco2

preco1_2_iguais_menor = preco1 == preco2 and preco1 < preco3
preco1_2_iguais_maior = preco1 == preco2 and preco1 > preco3

preco1_3_iguas_menor = preco1 == preco3 and preco1 < preco2
preco1_3_iguas_maior = preco1 == preco3 and preco1 > preco2

preco2_3_iguais_menor = preco2 == preco3 and preco2 < preco1
preco2_3_iguais_maior = preco2 == preco3 and preco2 > preco1

if preco1_menor:
  print(f'Você deverá comprar o primeiro produto')
elif preco2_menor:
  print(f'Você deverá comprar o segundo produto')
elif preco3_menor:
  print(f'Você deverá comprar o terceiro produto')
elif preco1_2_iguais_menor:
  print("Você pode escolher comprar ou o produto 1 ou o produto 2, seus preços são equivalentes")
elif preco1_2_iguais_maior:
  print(f'Você deverá comprar o terceiro produto')
elif preco1_3_iguas_menor:
  print("Você pode escolher comprar ou o produto 1 ou o produto 3, seus preços são equivalentes")
elif preco1_3_iguas_maior:
  print(f'Você deverá comprar o segundo produto')
elif preco2_3_iguais_menor:
  print("Você pode escolher comprar ou o produto 2 ou o produto 3, seus preços são equivalentes")
elif preco2_3_iguais_maior:
  print(f'Você deverá comprar o primeiro produto')
else:
  print("O preço dos 3 produtos são equivalentes")

#exercício 07

num1 = float(input("Digite um número qualquer: "))
num2 = float(input("Digite um número qualquer: "))
num3 = float(input("Digite um número qualquer: "))

lista = [num1,num2, num3]
lista.sort(reverse=True)
#lista.reverse()
print(lista)

#exercico 08

turno_digitado = input("Em que turno você estuda? (digite apenas a primeira letra). ").upper()
matutino = turno_digitado == "M"
vespertino = turno_digitado == "V"
noturno = turno_digitado == "N"

if matutino:
  print("BOM DIA")
elif vespertino:
  print("BOA TARDE")
elif noturno:
  print("BOA NOITE")
else:
  print("Valor inválido")

#exercicio 09

salario_digitado = float(input("Digite seu salário atual: "))
salario_280 = salario_digitado > 0 and salario_digitado <= 280
salario_ate_700 = salario_digitado > 280 and salario_digitado <= 700
salario_ate_1500 = salario_digitado > 700 and salario_digitado <= 1500
salario_acima_1500 = salario_digitado > 1500

percentual_de_aumento_salario__ate_280 = "20%"
percentual_de_aumento_salario__ate_700 = "15%"
percentual_de_aumento_salario__ate_1500 = "10%"
percentual_de_aumento_salario__acima_1500 = "5%"

aumento_20 = 20/100
aumento_15 = 15/100
aumento_10 = 10/100
aumento_05 = 5/100

if salario_280:
  valor_do_aumento_salario = salario_digitado * aumento_20
  salario_final = salario_digitado + valor_do_aumento_salario
  print(f"O salário antes do ajuste é de {salario_digitado} reais. \n O percentual aplicado foi de {percentual_de_aumento_salario__ate_280}.\n O valor do aumento foi de {valor_do_aumento_salario} reais. \n O novo salário será de {salario_final}")

elif salario_ate_700:
  valor_do_aumento_salario = salario_digitado * aumento_15
  salario_final = salario_digitado + valor_do_aumento_salario
  print(f"O salário antes do ajuste é de {salario_digitado} reais. \n O percentual aplicado foi de {percentual_de_aumento_salario__ate_700}.\n O valor do aumento foi de {valor_do_aumento_salario} reais. \n O novo salário será de {salario_final}")

elif salario_ate_1500:
  valor_do_aumento_salario = salario_digitado * aumento_10
  salario_final = salario_digitado + valor_do_aumento_salario
  print(f"O salário antes do ajuste é de {salario_digitado} reais. \n O percentual aplicado foi de {percentual_de_aumento_salario__ate_1500}.\n O valor do aumento foi de {valor_do_aumento_salario} reais. \n O novo salário será de {salario_final}")

elif salario_acima_1500:
  valor_do_aumento_salario = salario_digitado * aumento_05
  salario_final = salario_digitado + valor_do_aumento_salario
  print(f"O salário antes do ajuste é de {salario_digitado} reais. \n O percentual aplicado foi de {percentual_de_aumento_salario__acima_1500}.\n O valor do aumento foi de {valor_do_aumento_salario} reais. \n O novo salário será de {salario_final}")

else:
  print("Informçao inválida")

#exercicio 10

lado1 = float(input("Digite o comprimento do lado1 do triangulo: "))
lado2 = float(input("Digite o comprimento do lado2 do triangulo: "))
lado3 = float(input("Digite o comprimento do lado3 do triangulo: "))

forma_triangulo_se = (lado1 + lado2) > lado3 or (lado1 + lado3) > lado2 or (lado2 + lado3) > lado1
equilatero = lado1 == lado2 == lado3
isoceles = lado1 == lado2 or lado1 ==lado3 or lado2 == lado1
escaleno = lado1 != lado2 != lado3

if forma_triangulo_se and equilatero:
  print("Esse triângulo é equilátero")
elif forma_triangulo_se and isoceles:
  print("Esse triângulo é isóceles")
elif forma_triangulo_se and escaleno:
  print("Esse triângulo é escaleno")
else:
  print("Os lados indicados não formam um triangulo")

"""

*   Aula 03 - Estrutura de repetição

"""

#exercicio 01

nota = float(input("Digite uma nota entre 0 e 10: "))
nota_invalida = nota < 0 or nota >10

while nota_invalida:
  nota = float(input("Digite uma nota válida: "))
  nota_invalida = nota < 0 or nota >10

#exercicio 02

usuario = input("Digite o nome de usuário: ").lower()
senha = input("Digite sua senha: ").lower()

senha_invalida = usuario == senha

while senha_invalida:
  print("Sua senha não pode ser igual ao nome de usuário, cadastre novamente.")
  usuario = input("Digite o nome de usuário: ").lower()
  senha = input("Digite sua senha: ").lower()
  senha_invalida = usuario == senha

#exercicio 03

nome_digitado = input("Digite seu nome: ").lower()
idade_digitada = int(input("DIgite sua idade: "))
salario_digitado = float(input("Digite seu salário: "))
sexo_biologico = input("Digite a inicial do seu sexo biológico: ").lower()
estado_civil_digitado = input("Digite seu estádo civil atual (s - solteiro; c - casado; d - divorciado; v - viúvo )").lower()

nome_digitado_invalido = len(nome_digitado) < 3
idade_digitada_invalido = idade_digitada < 0 or idade_digitada > 150
salario_digitado_invalido = salario_digitado < 0
sexo_biologico_invalido = sexo_biologico != 'f' and sexo_biologico != "m"
estado_civil_digitado_invalido = estado_civil_digitado != "s" and estado_civil_digitado != "c" and estado_civil_digitado != "d" and estado_civil_digitado != "v"

while nome_digitado_invalido:
  print("Nome inválido, digite novamente a informacão.")
  nome_digitado = input("Digite seu nome: ").lower()
  nome_digitado_invalido = len(nome_digitado) < 3

while idade_digitada_invalido:
  print("idade inválida, digite novamente a informacão.")
  idade_digitada = int(input("Digite sua idade: "))
  idade_digitada_invalido = idade_digitada < 0 or idade_digitada > 150

while salario_digitado_invalido:
  print("Salário inválido, digite novamente a informação.")
  salario_digitado = float(input("Digite seu salário: "))
  salario_digitado_invalido = salario_digitado < 0

while sexo_biologico_invalido:
  print("Sexo biológico inválido, digite novamente a informação.")
  sexo_biologico = input("Digite a inicial do seu sexo biológico: ").lower()
  sexo_biologico_invalido = sexo_biologico != 'f' and sexo_biologico != "m"

while estado_civil_digitado_invalido:
  print("Estado civil inválido, digite novamente a informação.")
  estado_civil_digitado = input("Digite seu estádo civil atual (s - solteiro; c - casado; d - divorciado; v - viúvo )").lower()
  estado_civil_digitado_invalido = estado_civil_digitado != "s" and estado_civil_digitado != "c" and estado_civil_digitado != "d" and estado_civil_digitado != "v"


print("Muito obrigada, suas informações foram salvas em nosso sistema.")

#exercico 04

pop_pais_A = 80000
pop_pais_B = 200000
qntd_anos = 0

tx_cresc_A = 3/100
tx_cresc_B = 1.5/100

'''aumento_pop_A = pop_pais_A * tx_cresc_A
aumento_pop_B = pop_pais_B * tx_cresc_B

pop_A_atualizada = pop_pais_A + aumento_pop_A
pop_B_atualizada = pop_pais_B + aumento_pop_B'''

pop_diferente_entre_AB = pop_pais_A != pop_pais_B

while pop_diferente_entre_AB:

  aumento_pop_A = pop_pais_A * tx_cresc_A
  aumento_pop_B = pop_pais_B * tx_cresc_B

  pop_A_atualizada = pop_pais_A + aumento_pop_A
  pop_B_atualizada = pop_pais_B + aumento_pop_B

  qntd_anos += 1

  pop_pais_A = pop_A_atualizada
  pop_pais_B = pop_B_atualizada

  pop_diferente_entre_AB = pop_A_atualizada != pop_B_atualizada

print(f"Para a população do pais A ser igual a população do pais B demorou {qntd_anos} anos.")

#exercicio 05
pop_pais_A = float(input("Digite a população do país A"))
pop_pais_B = float(input("Digite a população do país B"))
qntd_anos = 0

tx_cresc_A = float(input("Digite a tx crescimento do país A"))
tx_cresc_B = float(input("Digite a tx crescimento do país B"))

tx_cresc_A_transformada = tx_cresc_A/100
tx_cresc_B_transformada = tx_cresc_B/100

pop_diferente_entre_AB = pop_pais_A != pop_pais_B

while pop_diferente_entre_AB:

  aumento_pop_A = pop_pais_A * tx_cresc_A_transformada
  aumento_pop_B = pop_pais_B * tx_cresc_B_transformada

  pop_A_atualizada = pop_pais_A + aumento_pop_A
  pop_B_atualizada = pop_pais_B + aumento_pop_B

  qntd_anos += 1

  pop_pais_A = pop_A_atualizada
  pop_pais_B = pop_B_atualizada

  pop_diferente_entre_AB = pop_A_atualizada != pop_B_atualizada

print(f"Para a população do pais A ser igual a população do pais B demorou {qntd_anos} anos.")

#exercicio06

n = 0
continuar = n != 21

while continuar:
  print(n)
  n+=1
  continuar = n != 21

#exercicio 06.2

n = 0
continuar = n != 21

while continuar:
  print(n, end=" ")
  n+=1
  continuar = n != 21

#exercicio 07
contador = 0
num = float(input("Digite um número qualquer: "))
continua = contador != 5
maior_num = num

while continua:
  print(num)
  num = float(input("Digite um número qualquer: "))
  if num > maior_num:
    maior_num = num
  contador += 1
  continua = contador != 4

print(f"O maior número digitado foi {maior_num}")

#exercicio 08

contador = 1
num = 0
soma = 0
media = num/contador
continua = contador < 5

while continua:
  num = float(input("Digite um número qualquer: "))
  soma += num
  media = soma/contador
  contador +=1
  continua = contador < 6

print(soma)
print(media)

#exercicio 09

contador = 0
continua = contador <50
is_impar = contador%2 != 0

while continua:
  if is_impar:
    print(contador)
  else:
    print(" ")
  contador+=1
  continua = contador <50
  is_impar = contador%2 != 0

# exercicio 10

num = int(input("Deseja calcular a tabuada de qual número? "))
contador = 0
continua = contador < 11

while continua:
  print(f"{num} x {contador} = {num*contador}")
  contador+=1
  continua = contador < 11

#exercicio 11

caixa_aberto = input("Deseja iniciar outro atendimento? (sim/não) ").lower()
preco = 1.99
continua = caixa_aberto == "sim"

while continua:
  qntd_itens_comprados = int(input("Digite a quantidade de itens que o cliente está comprando"))
  total_compras = preco*qntd_itens_comprados
  print(f"O valor das compras foi de {total_compras} reais.")
  caixa_aberto = input("Deseja iniciar outro atendimento? (sim/não) ").lower()
  continua = caixa_aberto == "sim"

print("Atendimento do dia encerrado")

"""Aula 04

*   Aula 04 - Loop for, listas, índices, iterações de listas, métodos de listas
"""

#exercicio 01

lista = ["a", "b", "c", "d"]

for item in lista:
  print(item)

# exercicio 02

lista = ["a", "b", "c", "d"]
contador = 0
limite_lista = contador < len(lista)


while limite_lista:
  print(lista[contador])
  contador += 1
  limite_lista = contador < len(lista)

#exercicio 03

lista = []
limite_lista = int(input("Digite um número qualquer"))

lista = list(range(limite_lista))
print(lista)

#exercicio 04
n = 0
lista_numeros = [1,2,3,4,5,6,7,8]

for item in lista_numeros:
  if item %2 == 0:
    n += 1
print(n)

#exercicio 05

lista_numeros = [1,2,98,8,3]
maior = 0

for item in lista_numeros:
  if item > maior:
    maior = item

print(maior)

#exercicio 06

lista_numeros = [1,8,67,5,43,9]
maior = max(lista_numeros)
print(maior)

#exercicio 07

lista_a = [1,2,3,4]
lista_b = [2,3,4,5]
lista_c = []


for x,y in zip(lista_a, lista_b):
  lista_c.append(x+y)

print(lista_c)

#exercicio 08

lista_a = [1,2,3,4]
lista_b = [2,3,4,5]
lista_c = []


for x,y in zip(lista_a, lista_b):
  lista_c.append(x*y)

print(lista_c)

#exercicio 09
contador = 0
lista_num = []
adiciona_lista = contador < 5

while adiciona_lista:
  item_lista = input("Digite um número")
  lista_num.append(item_lista)
  contador += 1
  adiciona_lista = contador < 5

print(lista_num)

#exercicio 10
for item in range(len(lista_num)):
  lista_num[item] = float(lista_num[item])

print(lista_num)

#exercicio 11
notas = []
qntd_notas = 0
continua = qntd_notas < 4
soma_nota = 0

while continua:
  nota_digitada = float(input("Digite a nota do aluno"))
  notas.append(nota_digitada)
  qntd_notas += 1
  soma_nota += nota_digitada
  continua = qntd_notas < 4

media = soma_nota/qntd_notas

print(notas)
print(soma_nota)
print(media)